/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingSignInRouteImport } from './routes/onboarding_.sign-in'
import { Route as AppWorkspacesRouteImport } from './routes/_app.workspaces'
import { Route as AppScheduledJobsRouteImport } from './routes/_app.scheduled-jobs'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppMigrateRouteImport } from './routes/_app.migrate'
import { Route as WorkspacesWorkspaceIdVscodeRouteImport } from './routes/workspaces.$workspaceId.vscode'
import { Route as AppWorkspacesElectricTestRouteImport } from './routes/_app.workspaces_.electric-test'
import { Route as AppWorkspacesCreateRouteImport } from './routes/_app.workspaces_.create'
import { Route as AppWorkspacesWorkspaceIdRouteImport } from './routes/_app.workspaces_.$workspaceId'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app.projects.$projectId'
import { Route as AppProjectsProjectIdIssuesIssueIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId'
import { Route as AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.workspaces.create.$draftId'
import { Route as AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.workspaces.$workspaceId'
import { Route as AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport } from './routes/_app.projects.$projectId_.issues.$issueId_.workspaces.create.$draftId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingSignInRoute = OnboardingSignInRouteImport.update({
  id: '/onboarding_/sign-in',
  path: '/onboarding/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspacesRoute = AppWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => AppRoute,
} as any)
const AppScheduledJobsRoute = AppScheduledJobsRouteImport.update({
  id: '/scheduled-jobs',
  path: '/scheduled-jobs',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppMigrateRoute = AppMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => AppRoute,
} as any)
const WorkspacesWorkspaceIdVscodeRoute =
  WorkspacesWorkspaceIdVscodeRouteImport.update({
    id: '/workspaces/$workspaceId/vscode',
    path: '/workspaces/$workspaceId/vscode',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppWorkspacesElectricTestRoute =
  AppWorkspacesElectricTestRouteImport.update({
    id: '/workspaces_/electric-test',
    path: '/workspaces/electric-test',
    getParentRoute: () => AppRoute,
  } as any)
const AppWorkspacesCreateRoute = AppWorkspacesCreateRouteImport.update({
  id: '/workspaces_/create',
  path: '/workspaces/create',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkspacesWorkspaceIdRoute =
  AppWorkspacesWorkspaceIdRouteImport.update({
    id: '/workspaces_/$workspaceId',
    path: '/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIdIssuesIssueIdRoute =
  AppProjectsProjectIdIssuesIssueIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId',
    path: '/projects/$projectId/issues/$issueId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/workspaces/create/$draftId',
    path: '/projects/$projectId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute =
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId',
    path: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute =
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport.update({
    id: '/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId',
    path: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/migrate': typeof AppMigrateRoute
  '/notifications': typeof AppNotificationsRoute
  '/scheduled-jobs': typeof AppScheduledJobsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/migrate': typeof AppMigrateRoute
  '/notifications': typeof AppNotificationsRoute
  '/scheduled-jobs': typeof AppScheduledJobsRoute
  '/workspaces': typeof AppWorkspacesRoute
  '/onboarding/sign-in': typeof OnboardingSignInRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/workspaces/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/workspaces/create': typeof AppWorkspacesCreateRoute
  '/workspaces/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/projects/$projectId/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/projects/$projectId/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/projects/$projectId/issues/$issueId/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_app/migrate': typeof AppMigrateRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/scheduled-jobs': typeof AppScheduledJobsRoute
  '/_app/workspaces': typeof AppWorkspacesRoute
  '/onboarding_/sign-in': typeof OnboardingSignInRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/workspaces_/$workspaceId': typeof AppWorkspacesWorkspaceIdRoute
  '/_app/workspaces_/create': typeof AppWorkspacesCreateRoute
  '/_app/workspaces_/electric-test': typeof AppWorkspacesElectricTestRoute
  '/workspaces/$workspaceId/vscode': typeof WorkspacesWorkspaceIdVscodeRoute
  '/_app/projects/$projectId_/issues/$issueId': typeof AppProjectsProjectIdIssuesIssueIdRoute
  '/_app/projects/$projectId_/workspaces/create/$draftId': typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/migrate'
    | '/notifications'
    | '/scheduled-jobs'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/migrate'
    | '/notifications'
    | '/scheduled-jobs'
    | '/workspaces'
    | '/onboarding/sign-in'
    | '/projects/$projectId'
    | '/workspaces/$workspaceId'
    | '/workspaces/create'
    | '/workspaces/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/projects/$projectId/issues/$issueId'
    | '/projects/$projectId/workspaces/create/$draftId'
    | '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
    | '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/onboarding'
    | '/_app/migrate'
    | '/_app/notifications'
    | '/_app/scheduled-jobs'
    | '/_app/workspaces'
    | '/onboarding_/sign-in'
    | '/_app/projects/$projectId'
    | '/_app/workspaces_/$workspaceId'
    | '/_app/workspaces_/create'
    | '/_app/workspaces_/electric-test'
    | '/workspaces/$workspaceId/vscode'
    | '/_app/projects/$projectId_/issues/$issueId'
    | '/_app/projects/$projectId_/workspaces/create/$draftId'
    | '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
    | '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  OnboardingSignInRoute: typeof OnboardingSignInRoute
  WorkspacesWorkspaceIdVscodeRoute: typeof WorkspacesWorkspaceIdVscodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding_/sign-in': {
      id: '/onboarding_/sign-in'
      path: '/onboarding/sign-in'
      fullPath: '/onboarding/sign-in'
      preLoaderRoute: typeof OnboardingSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces': {
      id: '/_app/workspaces'
      path: '/workspaces'
      fullPath: '/workspaces'
      preLoaderRoute: typeof AppWorkspacesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scheduled-jobs': {
      id: '/_app/scheduled-jobs'
      path: '/scheduled-jobs'
      fullPath: '/scheduled-jobs'
      preLoaderRoute: typeof AppScheduledJobsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/migrate': {
      id: '/_app/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof AppMigrateRouteImport
      parentRoute: typeof AppRoute
    }
    '/workspaces/$workspaceId/vscode': {
      id: '/workspaces/$workspaceId/vscode'
      path: '/workspaces/$workspaceId/vscode'
      fullPath: '/workspaces/$workspaceId/vscode'
      preLoaderRoute: typeof WorkspacesWorkspaceIdVscodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspaces_/electric-test': {
      id: '/_app/workspaces_/electric-test'
      path: '/workspaces/electric-test'
      fullPath: '/workspaces/electric-test'
      preLoaderRoute: typeof AppWorkspacesElectricTestRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces_/create': {
      id: '/_app/workspaces_/create'
      path: '/workspaces/create'
      fullPath: '/workspaces/create'
      preLoaderRoute: typeof AppWorkspacesCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/workspaces_/$workspaceId': {
      id: '/_app/workspaces_/$workspaceId'
      path: '/workspaces/$workspaceId'
      fullPath: '/workspaces/$workspaceId'
      preLoaderRoute: typeof AppWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId': {
      id: '/_app/projects/$projectId_/issues/$issueId'
      path: '/projects/$projectId/issues/$issueId'
      fullPath: '/projects/$projectId/issues/$issueId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/workspaces/create/$draftId'
      path: '/projects/$projectId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/workspaces/$workspaceId'
      path: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      fullPath: '/projects/$projectId/issues/$issueId/workspaces/$workspaceId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId': {
      id: '/_app/projects/$projectId_/issues/$issueId_/workspaces/create/$draftId'
      path: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      fullPath: '/projects/$projectId/issues/$issueId/workspaces/create/$draftId'
      preLoaderRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMigrateRoute: typeof AppMigrateRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppScheduledJobsRoute: typeof AppScheduledJobsRoute
  AppWorkspacesRoute: typeof AppWorkspacesRoute
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppWorkspacesWorkspaceIdRoute: typeof AppWorkspacesWorkspaceIdRoute
  AppWorkspacesCreateRoute: typeof AppWorkspacesCreateRoute
  AppWorkspacesElectricTestRoute: typeof AppWorkspacesElectricTestRoute
  AppProjectsProjectIdIssuesIssueIdRoute: typeof AppProjectsProjectIdIssuesIssueIdRoute
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdWorkspacesCreateDraftIdRoute
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute: typeof AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMigrateRoute: AppMigrateRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppScheduledJobsRoute: AppScheduledJobsRoute,
  AppWorkspacesRoute: AppWorkspacesRoute,
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppWorkspacesWorkspaceIdRoute: AppWorkspacesWorkspaceIdRoute,
  AppWorkspacesCreateRoute: AppWorkspacesCreateRoute,
  AppWorkspacesElectricTestRoute: AppWorkspacesElectricTestRoute,
  AppProjectsProjectIdIssuesIssueIdRoute:
    AppProjectsProjectIdIssuesIssueIdRoute,
  AppProjectsProjectIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdWorkspacesCreateDraftIdRoute,
  AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute:
    AppProjectsProjectIdIssuesIssueIdWorkspacesWorkspaceIdRoute,
  AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute:
    AppProjectsProjectIdIssuesIssueIdWorkspacesCreateDraftIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  OnboardingSignInRoute: OnboardingSignInRoute,
  WorkspacesWorkspaceIdVscodeRoute: WorkspacesWorkspaceIdVscodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
